[keemena_public_tokenizer_assets_v1]
git-tree-sha1 = "0293c813181ade29e0c88e0e48015f201d89ddeb"
lazy = true
[[keemena_public_tokenizer_assets_v1.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/keemena_public_tokenizer_assets_v1-0293c813181ade29e0c88e0e48015f201d89ddeb.tar.gz"
sha256 = "37a377b41e1e24a663de3ebf0bc9d0ca8e12a6b22d6b07fee5cecc5b99c365c4"

[mistral_v1_sentencepiece]
git-tree-sha1 = "269e5a6e7e9b2a3a36c5aa056efec18d6ea94ce2"
lazy = true
[[mistral_v1_sentencepiece.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v1_sentencepiece-269e5a6e7e9b2a3a36c5aa056efec18d6ea94ce2.tar.gz"
sha256 = "49d24203cfd7195237ed3595e8251785d1ad1bd5ab1adc49255c7abdc15ca56d"

[mistral_v3_sentencepiece]
git-tree-sha1 = "c2984d8a6de8079429b6b48190d7d6b21edd2d46"
lazy = true
[[mistral_v3_sentencepiece.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v3_sentencepiece-c2984d8a6de8079429b6b48190d7d6b21edd2d46.tar.gz"
sha256 = "d43d8d6a1829e9ccb98e9aefe4f9234dc98753424e0024e4b3a81869b5c2ea1b"

[phi2_bpe]
git-tree-sha1 = "06534a35136d674431905aaa2c68622f4d1fe3cf"
lazy = true
[[phi2_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/phi2_bpe-06534a35136d674431905aaa2c68622f4d1fe3cf.tar.gz"
sha256 = "dd144c774832fc80041c99d6abf8eb531452011eda82f08b30a3982e4a7c48f6"

[roberta_base_bpe]
git-tree-sha1 = "357ad7fbb29c6febed739af6edf0b8a2b982178f"
lazy = true
[[roberta_base_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/roberta_base_bpe-357ad7fbb29c6febed739af6edf0b8a2b982178f.tar.gz"
sha256 = "8cdca06e7641c1be82205eeccd3293d72294aafbabd28a2e90b967f2e825c90b"

[xlm_roberta_base_sentencepiece_bpe]
git-tree-sha1 = "e2419ed7e6f3c6a6784100351efe73f588ea2a5f"
lazy = true
[[xlm_roberta_base_sentencepiece_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/xlm_roberta_base_sentencepiece_bpe-e2419ed7e6f3c6a6784100351efe73f588ea2a5f.tar.gz"
sha256 = "4f2471126f7635dc4f47c9ecafe9c925b1f2e17bc9ee5202c54bacebfacc4656"
