[bert_base_multilingual_cased_wordpiece]
git-tree-sha1 = "de4c8f7815758debcdb87ea551e9fb750ee62a4e"
lazy = true

    [[bert_base_multilingual_cased_wordpiece.download]]
    sha256 = "4c0bdb53ecc063eed8084c93f85eb369b32b02060bdb8a95bf73eb32e6d07c20"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/bert_base_multilingual_cased_wordpiece-de4c8f7815758debcdb87ea551e9fb750ee62a4e.tar.gz"

[keemena_public_tokenizer_assets_v1]
git-tree-sha1 = "0293c813181ade29e0c88e0e48015f201d89ddeb"
lazy = true

    [[keemena_public_tokenizer_assets_v1.download]]
    sha256 = "37a377b41e1e24a663de3ebf0bc9d0ca8e12a6b22d6b07fee5cecc5b99c365c4"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/keemena_public_tokenizer_assets_v1-0293c813181ade29e0c88e0e48015f201d89ddeb.tar.gz"

[mistral_v1_sentencepiece]
git-tree-sha1 = "6c533f8c5611485d9e6a82ec015ed935b5201eeb"
lazy = true

    [[mistral_v1_sentencepiece.download]]
    sha256 = "7e13136769c28844190f7755d5272028670cab47778ace386321fdedbc667670"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v1_sentencepiece-6c533f8c5611485d9e6a82ec015ed935b5201eeb.tar.gz"

[mistral_v3_sentencepiece]
git-tree-sha1 = "287381bd6871378a9061322a315915021b7f8e24"
lazy = true

    [[mistral_v3_sentencepiece.download]]
    sha256 = "c9f6354c9da6354cbea8b03bcb5d6ee6e4322cb891726a92a5a60937e1af1c6c"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v3_sentencepiece-287381bd6871378a9061322a315915021b7f8e24.tar.gz"

[phi2_bpe]
git-tree-sha1 = "1d2e2dfbaa1a3fd2d16725c508e545bd12af56ee"
lazy = true

    [[phi2_bpe.download]]
    sha256 = "4a5cd17d1c44295f893d8390e4824f310ee9ced53ce02a6ec92dcf080279636c"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/phi2_bpe-1d2e2dfbaa1a3fd2d16725c508e545bd12af56ee.tar.gz"

[qwen2_5_bpe]
git-tree-sha1 = "b6c5d815f62c359f2d51a5b57ecfe2adde46a57f"
lazy = true

    [[qwen2_5_bpe.download]]
    sha256 = "4a7e6db7af168b1fdf03e4712bcde1fa277e42c5795d9c4858e14e058dcb8cb2"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/qwen2_5_bpe-b6c5d815f62c359f2d51a5b57ecfe2adde46a57f.tar.gz"

[roberta_base_bpe]
git-tree-sha1 = "0803189275067a256ffc63e496619533126a725d"
lazy = true

    [[roberta_base_bpe.download]]
    sha256 = "a6f52537f5c4c156954e384392fa2f198b76ad4e8aa43a0bbd989b56146fdcc3"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/roberta_base_bpe-0803189275067a256ffc63e496619533126a725d.tar.gz"

[xlm_roberta_base_sentencepiece_bpe]
git-tree-sha1 = "003128ccc485a5a02d22425a44fff6ee1186112c"
lazy = true

    [[xlm_roberta_base_sentencepiece_bpe.download]]
    sha256 = "b751b6617829324f12fbf7d59b79f112aa4733dc3df67311915fdbd5458e5829"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/xlm_roberta_base_sentencepiece_bpe-003128ccc485a5a02d22425a44fff6ee1186112c.tar.gz"
