[keemena_public_tokenizer_assets_v1]
git-tree-sha1 = "0293c813181ade29e0c88e0e48015f201d89ddeb"
lazy = true

    [[keemena_public_tokenizer_assets_v1.download]]
    sha256 = "37a377b41e1e24a663de3ebf0bc9d0ca8e12a6b22d6b07fee5cecc5b99c365c4"
    url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/keemena_public_tokenizer_assets_v1-0293c813181ade29e0c88e0e48015f201d89ddeb.tar.gz"

[mistral_v1_sentencepiece]
git-tree-sha1 = "dc168b06570078cf8161c46005a7630eea85791d"
lazy = true
[[mistral_v1_sentencepiece.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v1_sentencepiece-dc168b06570078cf8161c46005a7630eea85791d.tar.gz"
sha256 = "1bb08805227d966e38c2848fd744fd936b6bead2d63ae5ec19264e0971baa0df"

[mistral_v3_sentencepiece]
git-tree-sha1 = "6e61b4af27187d0288e82a08d60dcab53e1a32cb"
lazy = true
[[mistral_v3_sentencepiece.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/mistral_v3_sentencepiece-6e61b4af27187d0288e82a08d60dcab53e1a32cb.tar.gz"
sha256 = "87df7c8f7908ebb6d00050d1370cc4015a2de7de9a8c575dbe0cad2671934493"

[phi2_bpe]
git-tree-sha1 = "4959342b5f191d8cff8904d5be8fa506401b3ed5"
lazy = true
[[phi2_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/phi2_bpe-4959342b5f191d8cff8904d5be8fa506401b3ed5.tar.gz"
sha256 = "cc2b5dd9cd1783a46b0573f44042fe706e6937c717909ebe375afac57fffdf96"

[qwen2_5_bpe]
git-tree-sha1 = "7bc82d46bc42b7735331b0ab88022d547bbbc8b0"
lazy = true
[[qwen2_5_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/qwen2_5_bpe-7bc82d46bc42b7735331b0ab88022d547bbbc8b0.tar.gz"
sha256 = "82d93731a856981899ff84b2c6423b91ee2b7e0deb330b8a7b41c8df6f6c674c"

[roberta_base_bpe]
git-tree-sha1 = "2f75bf5df044cac2868496b3cc5b7b5e4f407a3a"
lazy = true
[[roberta_base_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/roberta_base_bpe-2f75bf5df044cac2868496b3cc5b7b5e4f407a3a.tar.gz"
sha256 = "8e38d3b5f5fb2e4ed4c2e628754060a93dda2a515ea06a05c22e4c7a2a7115b7"

[xlm_roberta_base_sentencepiece_bpe]
git-tree-sha1 = "e73ecd7b98b104d6d3a116a52f023437e79b2c5b"
lazy = true
[[xlm_roberta_base_sentencepiece_bpe.download]]
url = "https://github.com/mantzaris/KeemenaSubwords.jl/releases/download/tokenizer-artifacts-v1/xlm_roberta_base_sentencepiece_bpe-e73ecd7b98b104d6d3a116a52f023437e79b2c5b.tar.gz"
sha256 = "38ffae75ff4ec350cd8de0f761d752ecd7d323b3020e09be5b5dc124cfa47998"
