name = "KeemenaSubwords"
uuid = "891fdae5-3dc6-4d0d-8da0-c6f1d38b32bd"
authors = ["Alexander V. Mantzaris"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.10"
